# Generated by Django 3.2 on 2024-01-01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                ("is_superuser", models.BooleanField(default=False, help_text="Designates that this user has all permissions without explicitly assigning them.", verbose_name="superuser status")),
                ("username", models.CharField(error_messages={"unique": "A user with that username already exists."}, help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.", max_length=150, unique=True, verbose_name="username")),
                ("first_name", models.CharField(blank=True, max_length=150, verbose_name="first name")),
                ("last_name", models.CharField(blank=True, max_length=150, verbose_name="last name")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="email address")),
                ("is_staff", models.BooleanField(default=False, help_text="Designates whether the user can log into this admin site.", verbose_name="staff status")),
                ("is_active", models.BooleanField(default=True, help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.", verbose_name="active")),
                ("date_joined", models.DateTimeField(auto_now_add=True, verbose_name="date joined")),
                ("english_name", models.CharField(blank=True, max_length=150)),
                ("scnx", models.CharField(blank=True, choices=[("SCN1", "SCN1"), ("SCN2", "SCN2")], max_length=10, null=True)),
                ("role", models.CharField(blank=True, choices=[("CM", "CM"), ("LCM", "LCM"), ("HOD", "HoD")], max_length=10, null=True)),
                ("groups", models.ManyToManyField(blank=True, help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.", related_name="user_set", related_query_name="user", to="auth.Group", verbose_name="groups")),
                ("user_permissions", models.ManyToManyField(blank=True, help_text="Specific permissions for this user.", related_name="user_set", related_query_name="user", to="auth.Permission", verbose_name="user permissions")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ile", models.CharField(max_length=100)),
                ("round_location", models.CharField(max_length=100)),
                ("region", models.CharField(blank=True, choices=[("CCN1", "CCN1"), ("CCN2", "CCN2"), ("CCN3", "CCN3"), ("CCN4", "CCN4")], max_length=10, null=True)),
                ("responsible_cm", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="customers_as_cm", to=settings.AUTH_USER_MODEL)),
                ("responsible_lcm", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="customers_as_lcm", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="SystemSetting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("auto_generation_enabled", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Work",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("period_year", models.IntegerField()),
                ("period_month", models.IntegerField()),
                ("bn_release_status", models.CharField(choices=[("OPEN", "Open"), ("FULL", "Full"), ("PARTIAL", "Partial"), ("NONE", "None")], default="OPEN", max_length=20)),
                ("comment", models.TextField(blank=True)),
                ("customer_region", models.CharField(blank=True, max_length=10, null=True)),
                ("assigned_lcm_scnx", models.CharField(blank=True, max_length=10, null=True)),
                ("assigned_cm", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="assigned_cm_works", to=settings.AUTH_USER_MODEL)),
                ("assigned_lcm", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="assigned_lcm_works", to=settings.AUTH_USER_MODEL)),
                ("customer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="invoice.customer")),
            ],
        ),
        migrations.CreateModel(
            name="WorkStep",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("step_no", models.IntegerField(choices=[(1, "Step 1"), (2, "Step 2"), (3, "Step 3"), (4, "Step 4")])),
                ("planned_due_date", models.DateField(blank=True, null=True)),
                ("actual_closed_date", models.DateField(blank=True, null=True)),
                ("step_status", models.CharField(choices=[("OPEN", "Open"), ("CLOSED", "Closed")], default="OPEN", max_length=10)),
                ("step_comment", models.TextField(blank=True)),
                ("work", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="invoice.work")),
            ],
        ),
        migrations.CreateModel(
            name="CustomerStepRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("step_no", models.IntegerField(choices=[(1, "Step 1"), (2, "Step 2"), (3, "Step 3"), (4, "Step 4")])),
                ("rule_type", models.CharField(choices=[("NO_RULE", "No Rule"), ("THIS_MONTH_DAY", "This Month Day"), ("NEXT_MONTH_DAY", "Next Month Day"), ("THIS_MONTH_NTH_WEEKDAY", "This Month Nth Weekday"), ("THIS_MONTH_LAST_NTH_DAY", "This Month Last Nth Day")], max_length=40)),
                ("day_of_month", models.IntegerField(blank=True, null=True)),
                ("nth", models.IntegerField(blank=True, null=True)),
                ("weekday", models.IntegerField(blank=True, null=True)),
                ("last_nth", models.IntegerField(blank=True, null=True)),
                ("customer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="invoice.customer")),
            ],
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(fields=("ile", "round_location"), name="unique_customer"),
        ),
        migrations.AddConstraint(
            model_name="customersteprule",
            constraint=models.UniqueConstraint(fields=("customer", "step_no"), name="unique_customer_step_rule"),
        ),
        migrations.AddConstraint(
            model_name="work",
            constraint=models.UniqueConstraint(fields=("customer", "period_year", "period_month"), name="unique_work_period"),
        ),
        migrations.AddConstraint(
            model_name="workstep",
            constraint=models.UniqueConstraint(fields=("work", "step_no"), name="unique_work_step"),
        ),
    ]
